## NUMPY ARRAY AND BASICS 


In [ ]:
import numpy as np


CREATING ARRAY FROM LIST

In [26]:
arr_1d = np.array([1,2,3,4,5])
print("1d array",arr_1d)


arr_2d = np.array([[1,2,3],
                [4,5,6]])
print("2d_array",arr_2d)

1d array [1 2 3 4 5]
2d_array [[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
print("1d array", arr_1d)

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("2d array", arr_2d)


1d array [1 2 3 4 5]
2d array [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [2]:
import numpy as np

py_list = [1,2,3]


print("python list multiplication",py_list*2)


np_array  = np.array([1,2,3]) #element wise multiplication
print("pyhon array multiplication",np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n List operation time : ", time.time()-start)

start = time.time()
np_array = np.arange(100000)*2
print("\n Numpy operation time : ", time.time()-start)

python list multiplication [1, 2, 3, 1, 2, 3]
pyhon array multiplication [2 4 6]

 List operation time :  0.006492137908935547

 Numpy operation time :  0.0007107257843017578


###  CREATING ARRAY FROM SCRATCH

In [ ]:
# in python array act as a mateix it is in same formate as row X column

zeros = np.zeros((3,4))    # array forme but with the ony num:-0
print("Zeros_array: \n", zeros)

Ones = np.ones((2,3))   # array forme but with the ony num:-1
print("Ones_array: \n",Ones)

full = np.full((2,2),7)   # the array forme but with secific number
print("full_array: \n",full)


random = np.random.random((2,3))  # the value random value come between 0-1
print("randon_array: \n",random)


sequesnce = np.arange(0,10,2)   # 10 is not included .
                                # this hepl us to make a sequesnce array
print("sequrnce_array: \n",sequesnce)




Zeros_array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones_array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full_array: 
 [[7 7]
 [7 7]]
randon_array: 
 [[0.77911671 0.2292229  0.4304481 ]
 [0.44615886 0.55394852 0.38083273]]
sequrnce_array: 
 [0 2 4 6 8]


### Vector,Matrix and Tensor

In [ ]:
vector = np.array([1,2,3])
print("vector: \n",vector)


matrix = np.array([[1,2,3],
                  [4,5,6]])
print("Matrix: \n",matrix)


tensor =  np.array([[[1,2],[3,4]],  # anything  more than 2D is tensor . The complication increase in the tensor 
                     [[5,6],[7,8]]])
print("tensor: \n",tensor)

vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [14]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape",arr.shape)
print("Dimesion",arr.ndim)
print("Size",arr.size)
print("Dtype",arr.dtype) 

Shape (2, 3)
Dimesion 2
Size 6
Dtype int64


### Array Reshaping

In [25]:
arr = np.arange(12)
print("Original: ",arr) 

Reshape = arr.reshape((3,4))
print("\n Reshaped_array: ", Reshape)


Flattened = Reshape.flatten()
print("Flattened_array: ",Flattened)


Raveled = Reshape.ravel()  # Return  view , insted of copy
print(" \n reval_array: ",Raveled)


# Transpose

Transponse = Reshape.transpose()
print("Transpose_Arrya: ",Transponse)



Original:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped_array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened_array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
 
 reval_array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose_Arrya:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
