### Numpy Array operatons


In [2]:
import numpy as np

In [3]:
arr  = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing",arr[2:7])
print("With step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With step [2 4 6 8]
Negative indexing 8


In [ ]:
arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element",arr_2D[1,2]) #its mean first row second element
print("Entire row: ",arr_2D[1])
print("Entire colmn",arr_2D[: , 1])  # : => it means the i selected all the row now i will j

Specific element 6
Entire row:  [4 5 6]
Entire colmn [2 5 8]


### Sorting
   

In [3]:
unsorted = np.array([3,2,5,4,7,6,9,8,1])
print("Sorted Array: ",np.sort(unsorted))

Sorted Array:  [1 2 3 4 5 6 7 8 9]


In [6]:
arr_2D_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column", np.sort(arr_2D_unsorted,axis=0 )) # this axis =0 sort the array in the cloumn wise top-bottom
print("Sorted 2D array by column", np.sort(arr_2D_unsorted,axis=0 ))  # this axis = 1 sort the array in the column wise left-right

Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]


## Filter

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers%2==0]
print("Even number: ",even_numbers)

Even number:  [ 2  4  6  8 10]


### Filter with mask

In [9]:
mask = numbers >5
print("numbers greater than 5 ",numbers[mask])

mask_1 = numbers%2==0
print("Even numbers ",numbers[mask_1])

numbers greater than 5  [ 6  7  8  9 10]
Even numbers  [ 2  4  6  8 10]


### Fancy indexing vs np.where()

In [11]:
indices = [0,2,4]
print(numbers[indices])


where_result = np.where(numbers > 5)
# print(where_result)
print("NP where", numbers[where_result])


[1 3 5]
NP where [ 6  7  8  9 10]


In [10]:
Condition_array = np.where(numbers > 5,numbers*1,numbers)
print(Condition_array)


[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
# <!-- if(numbers>5){
#     numbers*2
# }else{
#     numbers
# } -->

### Adding and removing data

In [13]:
arr1= np.array([1,2,3])
arr2 = np.array([4,5,6])

combined_array = np.concatenate((arr1,arr2))
print(combined_array)

[1 2 3 4 5 6]


### Array compatibility

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes True


In [ ]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row)) # vstack will going to add the rows
# print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col)) # hstack will going to add the coloumns
print("With new column",with_new_col)

[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [ ]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr , 2)
print(deleted)  # this print the array after deleting the element not the element

[1 2 4 5]
